### ISSUE TITLE
Bad vertical align of nav items

### ISSUE THREAD

**Issue by vasimi** [craigcook/frontierline-theme#24]
Search field is much lower than Explore and Categories. Explore and Categories aren't vertically centered, there is more space on the bottom than on the top.
<img width="951" alt="snimek obrazovky 2018-01-30 v 17 33 55" src="https://user-images.githubusercontent.com/9162439/35578255-cf83f48a-05e3-11e8-854c-a86130357195.png">

**Comment by MikkCZ** [comment]
Doesn't seem to me in Firefox. Probably some Safari/Webkit issue again? The search field position seems related to #23.

**Comment by vasimi** [comment]
In Firefox, it isn't so visible because the search bar has proper height, but links aren't vertically centered.

**Comment by MikkCZ** [comment]
As a CSS purist, can you make a PR please? ;)

**Comment by craigcook** [comment]
Fixed in 66d6875cdbca31d21ce0c194ec9b6b57e724ca08
