### ISSUE TITLE
Reduce the header height

### ISSUE THREAD

**Issue by MikkCZ** [craigcook/frontierline-theme#27]
The header image may take a lot of vertical space on the landing page (on post pages it's lower). It should be lower, either by configuration or at least when no image is set, or no page description is set.

@craigcook what is the reason for having the header space higher on the landing page than elsewhere?

**Comment by craigcook** [comment]
This was a design decision at an earlier stage to give a bit more branding prominence on the front page. I think we had different ideas for header images at that time and now the size change doesn't seem to matter as much. Let's make it the same on the front page by removing [this block of styling](https://github.com/craigcook/frontierline-theme/blob/master/themes/frontierline/sass/components/page-sections/_masthead.scss#L55).
