### ISSUE TITLE
Previous post buttons has right facing arrow

### ISSUE THREAD

**Issue by stephaniehobson** [craigcook/frontierline-theme#28]
<img width="482" alt="screen shot 2018-02-05 at 17 17 28" src="https://user-images.githubusercontent.com/854701/35837099-d12f6e0e-0a98-11e8-8175-cc53a7c8ed08.png">

The transform doesn't seem to work on items with a `display: inline` :(

**Comment by MikkCZ** [comment]
I can confirm. The best solution is to change the `content` to `"\25C2\00A0"` and remove `transform` from the `::before` element completely.
