### ISSUE TITLE
Posts from category and Latest posts are the same

### ISSUE THREAD

**Issue by vasimi** [craigcook/frontierline-theme#46]
Can be seen after the article, there are two columns and the content is the same (in Latest posts, there are only posts from the category). https://www.mozilla.cz/zpravicky/firefox-send-dostava-par-vylepseni/

**Comment by MikkCZ** [comment]
@craigcook I think this is fixed by https://github.com/craigcook/frontierline-theme/commit/0d690e98a51bb33d82e7352bec7d2d7fa91c6a69, right?

**Comment by craigcook** [comment]
Yes, this is fixed. I had missed this issue when it was opened. I should pay more attention. It's also a really simple bug I should have noticed and fixed ages ago... sorry.
