### ISSUE TITLE
Body-text font should be Inter

### ISSUE THREAD

**Issue by fitojb** [craigcook/frontierline-theme#55]
Per the new brand guidelines, as described [here](https://github.com/mozilla/protocol/issues/342#issuecomment-475324102).

Quoting from the [Typography](https://protocol.mozilla.org/fundamentals/typography.html) page of the Protocol design system:

> Zilla Slab and Inter are the standard typefaces on Mozilla branded websites.

Zilla Slab is designed for headings, and it is inadequate for body text due to its extremely reduced x-height. Quoting again, emphasis mine:

> We use [Zilla Slab] for our wordmark and as a _display font for headlines_ on Mozilla branded sites

**Comment by Sharma-palak** [comment]
Hi @fitojb , I am new to open source ,can I take this issue.
