### ISSUE TITLE
style.css is broken

### ISSUE THREAD

**Issue by selimsum** [craigcook/frontierline-theme#58]
dc8e3ff4b3c08b1aeeed82a74e307bf8060b22c3 broke frontierline-theme/themes/frontierline/style.css.

**Comment by ducwp** [comment]
Open file: frontierline\sass\pebbles\ _pebbles.scss then delete or add comment to line: 'includes/fonts/inter'.

Become: //'includes/fonts/inter'

Run compile again

**Comment by MikkCZ** [comment]
@craigcook this is fixed in https://github.com/craigcook/frontierline-theme/commit/a6c26883eae7a8ad17c04a911b49b185ed265e28, right?

**Comment by craigcook** [comment]
Yes, this is fixed. I included an error in a prior commit and managed to never noticed for way too long and finally fixed it months later (the version I uploaded to production worked, the one I committed to git had the error.) Sorry about that. 🤦
